# Generated by Django 2.2.5 on 2020-01-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_token'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('user', 'key')},
        ),
    ]
