# Generated by Django 2.2.5 on 2020-01-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200128_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='name',
        ),
    ]
