# Generated by Django 2.2.5 on 2020-01-31 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200131_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name': 'Token', 'verbose_name_plural': 'Tokens'},
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set(),
        ),
    ]
