# Generated by Django 2.2.5 on 2020-01-31 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200131_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('user', 'key')},
        ),
    ]
