# Generated by Django 2.2.2 on 2020-06-07 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_group_memebership'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemeberShip',
            new_name='MemberShip',
        ),
    ]
