# Generated by Django 2.2.2 on 2019-12-25 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Communties',
            new_name='Communities',
        ),
    ]
