# Generated by Django 2.2.2 on 2019-12-28 15:47

import communities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20191226_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communities',
            name='avatarimage',
            field=models.ImageField(blank=True, upload_to=communities.models.upload_location_avatarimage),
        ),
    ]
