# Generated by Django 2.2.5 on 2020-02-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_auto_20200127_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communities',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
