# Generated by Django 2.2.5 on 2020-03-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_communityhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityhistory',
            name='community',
        ),
        migrations.AddField(
            model_name='communityhistory',
            name='communityid',
            field=models.CharField(default='', max_length=10),
        ),
    ]
