# Generated by Django 2.2.5 on 2020-04-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0010_auto_20200407_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='communities',
            name='subscriber_count',
            field=models.PositiveIntegerField(default=0, verbose_name='subscriber count'),
        ),
    ]
