language: python
python:
  - "2.7"
  - "3.7"
services:
  - docker
before_install:
  - docker pull redis
  - docker run redis
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script: pytest
#Stop docker sevices
#after_script:
#  - docker stop $(docker ps -aq)