# Generated by Django 2.2.2 on 2020-06-21 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0029_taggedblogs'),
        ('communities', '0011_communities_subscriber_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVisitStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('visits', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ContentVisitStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits', models.BigIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.Communities')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('date', 'blog')},
            },
        ),
        migrations.CreateModel(
            name='CommentCountStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_count', models.BigIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.Communities')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('date', 'blog')},
            },
        ),
    ]
