# Generated by Django 2.2.2 on 2020-06-28 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0011_communities_subscriber_count'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySubscriberStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('rise', models.BigIntegerField(default=0)),
                ('fall', models.BigIntegerField(default=0)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.Communities')),
            ],
            options={
                'unique_together': {('date', 'community')},
            },
        ),
    ]
