# Generated by Django 2.2.2 on 2020-06-28 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0011_communities_subscriber_count'),
        ('blog', '0029_taggedblogs'),
        ('analytics', '0002_communitysubscriberstats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentCountStats',
            new_name='BlogCommentCountStats',
        ),
    ]
