# Generated by Django 2.2.2 on 2019-12-28 17:11

from django.db import migrations, models
import exposeunits.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exposeunits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('backgroundimage', models.ImageField(blank=True, upload_to=exposeunits.models.upload_location_backgroundimage)),
                ('avatarimage', models.ImageField(blank=True, upload_to=exposeunits.models.upload_location_avatarimage)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
