# Generated by Django 2.2.5 on 2020-02-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200205_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='references',
            name='blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='references',
            field=models.ManyToManyField(to='blog.References'),
        ),
        migrations.AlterField(
            model_name='references',
            name='refers',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
