# Generated by Django 2.2.5 on 2020-02-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200205_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='references',
            name='refers',
            field=models.CharField(blank=True, max_length=300, unique=True),
        ),
    ]
