# Generated by Django 2.2.5 on 2020-02-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200206_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='references',
            field=models.ManyToManyField(default=None, to='blog.References'),
        ),
    ]
