# Generated by Django 2.2.5 on 2020-02-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200207_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='references',
            field=models.ManyToManyField(to='blog.References'),
        ),
    ]
