# Generated by Django 2.2.5 on 2020-02-07 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blog_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='references',
            options={'ordering': ['refers']},
        ),
    ]
