# Generated by Django 2.2.5 on 2020-02-09 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blog_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='users',
        ),
    ]
