# Generated by Django 2.2.5 on 2020-03-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_references_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='references',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
