# Generated by Django 2.2.5 on 2020-03-27 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200327_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='references',
            name='description',
        ),
    ]
