# Generated by Django 2.2.5 on 2020-03-28 07:36

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_references_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to=blog.models.upload_location),
        ),
    ]
