# Generated by Django 2.2.5 on 2020-03-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_bloghistory_referencehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghistory',
            name='blog',
            field=models.CharField(max_length=10),
        ),
    ]
