# Generated by Django 2.2.5 on 2020-03-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200331_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloghistory',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='referencehistory',
            name='reference',
        ),
        migrations.AddField(
            model_name='bloghistory',
            name='blogid',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='referencehistory',
            name='referenceid',
            field=models.CharField(default='', max_length=10),
        ),
    ]
