# Generated by Django 2.2.5 on 2020-03-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200331_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghistory',
            name='blogid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='referencehistory',
            name='referenceid',
            field=models.CharField(max_length=10),
        ),
    ]
