# Generated by Django 2.2.5 on 2020-04-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20200331_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghistory',
            name='blogid',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='referencehistory',
            name='referenceid',
            field=models.CharField(max_length=30),
        ),
    ]
