# Generated by Django 2.2.2 on 2019-12-28 17:11

from django.db import migrations, models
import django.db.models.deletion
import expose.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exposeunits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('body', models.TextField(blank=True, max_length=5000)),
                ('image', models.ImageField(blank=True, upload_to=expose.models.upload_location)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('exposeunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exposeunits.Exposeunits')),
            ],
        ),
    ]
