# Generated by Django 2.2.5 on 2020-01-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expose', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expose',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
