# Generated by Django 2.2.5 on 2020-03-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expose', '0002_auto_20200127_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='expose',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
